### ISSUE TITLE
[Resultados] Bet on home team score is not covering the entire team card border

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#103]
A partezinha que mostra minha aposta não está cobrindo completamente a borda do card do time "da casa". Sobram alguns pixels.

**Comment by FelipeZNascimento** [comment]
É um problema de renderização dos browsers.. cada browser renderiza bordas e shadows de uma forma diferente e gera esse tipo de coisa.

Não tem muito o que eu possa fazer, infelizmente.
