### ISSUE TITLE
[Ranking] Description should be "Acerto Total" instead of "Acerto Completo"

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#105]
Mosca deveria ser "Acerto Total" em vez de "Acerto Completo" de acordo com as regras. Também parece que não precisa abreviar "Pts.", ou coloca uma glande nele também.

**Comment by FelipeZNascimento** [comment]
Precisa abreviar por causa da view mobile

![image](https://user-images.githubusercontent.com/24943990/196058767-176365e5-19ab-411a-bb53-45cfb568d6f7.png)
