### ISSUE TITLE
[Regras] Updates required on rules (see description)

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#107]
- Inscrição: centralizar texto da observação e deixar nossos contatos em duas colunas, assim como fez na seção Contato.
- Premiação: mudar o texto "Até 112 inscritos" para "Menos de 112 inscritos".
- Apostas: colocar meu e-mail no lugar do meu celular.
- FAQ:
---- O "a" de "até a Final" não tem crase.
---- Ajustar a resposta da pergunta "Todo o valor da inscrição será revertido em premiação?" porque está dando a entender que os 100 reais das extras estão incluídos nos 10%.
---- Adicionar no FAQ que preencher aposta com 1 vs. NADA é considerado aposta incompleta. É preciso apostar o valor 0.
- Contato: mesma observação sobre os ícones de WhatsApp e Telegram. Colocaria um título "Entre nos grupos do Bolão!".

**Comment by FelipeZNascimento** [comment]
Premiação: mudar o texto "Até 112 inscritos" para "Menos de 112 inscritos".


Aqui eu deixei "Até Até 112 inscritos" pra que ficasse do mesmo tamanho da "112+ inscritos..." senão fica estranho no celular.

**Comment by nelsonmotta** [comment]
Então teria que ser até 111 inscritos.
