### ISSUE TITLE
[Seleções] Updates on teams page (see description)

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#108]
SUGESTÕES:
- Colocar glandes nos botões de menu e "X" na página da seleção.
- Adicionar locais para popular com técnico e jogadores convocados.
- Deixar um espacinho entre a bandeira do país e o brasão.
- Permitir navegar da primeira seleção até a última com o botão < e vice-versa.

**Comment by FelipeZNascimento** [comment]
- Adicionar locais para popular com técnico e jogadores convocados.

Esse ficou pra depois

**Comment by nelsonmotta** [comment]
A bandeira e o brasão ainda estão coladinhos:

![Image](https://user-images.githubusercontent.com/37775892/197352386-ef40308e-e8b8-481b-9f39-349debe40039.png)

**Comment by nelsonmotta** [comment]
E o botão "Voltar à página anterior" está funcionando de forma estranha. Parece que ele está guardando na memória cada link que você navega na página de seleções e acaba passando por eles em vez de simplesmente voltar pra página anterior.

**Comment by nelsonmotta** [comment]
Vou criar um bug para o comentário acima, deixamos no backlog.

**Comment by FelipeZNascimento** [comment]
Então esse já pode mover pra próxima coluna?
