### ISSUE TITLE
[Home] Create web scrapper from Globoesporte 

### ISSUE THREAD

**Issue by FelipeZNascimento** [FelipeZNascimento/bolaocopa22#58]
https://ge.globo.com/futebol/copa-do-mundo/
https://dev.to/code_jedi/web-scraping-in-nodejs-2lkf

**Comment by laurisseau** [comment]
Hey, can I help with this?

What data would you like me to scrap?

**Comment by FelipeZNascimento** [comment]
> Hey, can I help with this?
> 
> What data would you like me to scrap?

Hey @laurisseau! I just saw your message.
Sorry for not replying it before.

What I'd like to scrape are the news from [here](https://ge.globo.com/futebol/copa-do-mundo/ultimas-noticias/). I don't know if you speak portuguese but it's all World Cup related news.

Even though your help would have been very much appreciated, I'm almost finishing it on my side. =/
If you like, I can open the PR later today and you take a look and improve on whatever you feel like it (as I have no experience on scrapping and this is my 1st try).

Anyhow I thank you for offering support.
Do you have any interest on this platform I'm building?
