### ISSUE TITLE
[Apostar] Take extraTime score into account when calculating points

### ISSUE THREAD

**Issue by FelipeZNascimento** [FelipeZNascimento/bolaocopa22#80]

**Comment by nelsonmotta** [comment]
Precisa ser feito algo aqui? Os gols de prorrogação serão salvos da mesma forma que os gols normais no BD, certo?

**Comment by FelipeZNascimento** [comment]
hmmmm é verdade. Não sei por que mas eu tava achando que tinha uma coluna para gols feitos na prorrogação.
Esse aqui pode ser fechado então.
