### ISSUE TITLE
[UserLogin] Forgot password confirm button is not available when e-mail is already filled

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#87]
Quando preencho meu e-mail e depois clico em "Esqueci a senha", o e-mail que já estava preenchido permanece, mas o botão de confirmar não é liberado. Só libera quando eu digito alguma coisa.

**Comment by nelsonmotta** [comment]
Quando preencho meu e-mail e depois clico em "Esqueci a senha", o e-mail que já estava preenchido permanece, mas o botão de confirmar não é liberado. Só libera quando eu digito alguma coisa.

**Comment by FelipeZNascimento** [comment]
Isso é pra evitar que a pessoa sobrecarregue o sistema apertando o botão X vezes.
