### ISSUE TITLE
[UserLogin] Error message appears even when a successful change of password occurs

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#89]
Quando tento trocar a senha usando a senha atual correta, a senha é trocada, mas aparece uma mensagem de "Erro na operação" em vez de mensagem de sucesso.

**Comment by nelsonmotta** [comment]
Ainda não resolveu.

**Comment by nelsonmotta** [comment]
Agora a mensagem veio correta. Porém quando terminei de trocar a senha, o e-mail sumiu do modal.

**Comment by FelipeZNascimento** [comment]
Acabei de fazer a troca da senha e parece-me tudo certo.
Tem algum passo extra pra reproduzir isso?

![image](https://user-images.githubusercontent.com/24943990/196385146-29815c7f-bbf7-48ff-984e-395486a7e83c.png)

**Comment by nelsonmotta** [comment]
Não consegui replicar mais, então vou fechar haha.
