### ISSUE TITLE
[UserLogin] User is not receiving the "Forgot Password" e-mail

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#90]
Não recebi o e-mail para recadastro de senha. Nem no spam. Também não recebi e-mail quando registrei uma conta nova.

**Comment by nelsonmotta** [comment]
Também não recebi e-mail quando registrei uma conta nova.

**Comment by FelipeZNascimento** [comment]
Testei agora e recebi. Consegue repetir o teste?

![image](https://user-images.githubusercontent.com/24943990/196056643-ad053a2c-bb41-4e4b-8570-a7a3f68aee7a.png)

**Comment by FelipeZNascimento** [comment]
A parte de enviar e-mail na criação de uma nova conta ainda não foi criada.

Issue criado aqui: https://github.com/FelipeZNascimento/bolaocopa22/issues/113

**Comment by nelsonmotta** [comment]
Quase tudo certo na parte de senha esquecida. Dois pontos para corrigir:
1) Quando clico para enviar o e-mail de reset de senha, o botão "Confirmar" permanece ativo, então consegui enviar múltiplos e-mails de reset de senha.


![Image](https://user-images.githubusercontent.com/37775892/196421991-7aa1d824-1024-4bee-8ed7-f283127750b1.png)

2) Quando cadastro com sucesso a nova senha, ainda fica disponível um botão "Confirmar" que, quando clicado, volta para a tela de escolha de nova senha. Nessa tela ele já dá token inválido e não permite trocar de novo, mas acho que faz mais sentido que esse botão mude para "Fazer login" e já encaminhe para o login. Nesse caso, as mensagens "Senha alterada com sucesso" e "Clique aqui para fazer o login" ficam redundantes, porque já temos o "Operação feita com sucesso" e teríamos o botão de fazer login.


![Image](https://user-images.githubusercontent.com/37775892/196422278-d28ec13f-17af-4f71-9433-454cf87a3ce6.png)


![Image](https://user-images.githubusercontent.com/37775892/196422384-6938adb6-ba75-4348-9145-bf7fe5ab9874.png)

**Comment by FelipeZNascimento** [comment]
1) Tá resolvido.

2) Mesclei suas sugestões.

- Deixei o botão com LOGIN que encaminha pra home e abre o popup de login;
- Tirei a toastzinha com "Operação feita com sucesso" e deixei a mensagem "Senha alterada com sucesso!"

**Comment by nelsonmotta** [comment]
Só consigo testar quando isso estiver em produção, porque o e-mail manda para prod.

**Comment by FelipeZNascimento** [comment]
> Só consigo testar quando isso estiver em produção, porque o e-mail manda para prod.

Se você meter `dev.` na frente do link, funciona também!
