### ISSUE TITLE
[UserLogin] "Forgot password" e-mail is sent even to an e-mail that is not registered

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#91]
Tentei o "Esqueci a Senha" com um e-mail que não estava cadastrado e apareceu a mensagem "Enviamos um e-mail com instruções para configurar sua nova senha.".

**Comment by FelipeZNascimento** [comment]
Por questões de segurança, eu não posso retornar "Email X não foi encontrado". Se eu retornasse isso, quem quer que esteja tentando abusar do sistema facilmente poderia descobrir se algum email está cadastrado ou não - e aí só precisaria descobrir a senha.

**Comment by nelsonmotta** [comment]
Então pelo menos troca o texto para "Se esse e-mail estiver cadastrado, enviamos um e-mail com instruções para configurar sua nova senha.".
