### ISSUE TITLE
[Resultados] Show user bets in Results tab even for matches that didn't start yet

### ISSUE THREAD

**Issue by nelsonmotta** [FelipeZNascimento/bolaocopa22#97]
SUGESTÃO: mostrar as apostas feitas pelo usuário na aba Resultados, mesmo para partidas ainda não iniciadas. Ajudaria a perceber que esqueceu de apostar ou está com alguma aposta incompleta.

**Comment by FelipeZNascimento** [comment]
Feito também para as partidas que aparecem na home.
